export default [
  { name: 'Karimunda', type: 'Climber', category: 'Bush Pepper', description: 'Popular cultivar known for yield.', price: 120, stock: 50 },
  { name: 'Naraya Pepper', type: 'Climber', category: 'Bush Pepper', description: 'Locally favored flavor profile.', price: 110, stock: 40 },
  { name: 'Kumbukkan', type: 'Climber', category: 'Bush Pepper', description: 'Strong aroma, robust growth.', price: 115, stock: 35 },
  { name: 'Randhalmunda', type: 'Climber', category: 'Bush Pepper', description: 'Good disease tolerance.', price: 130, stock: 30 },
  { name: 'Kairali', type: 'Climber', category: 'Bush Pepper', description: 'Balanced flavor and yield.', price: 125, stock: 30 },
  { name: 'Panniyur 1', type: 'Climber', category: 'Bush Pepper', description: 'High yielding selection.', price: 140, stock: 45 },
  { name: 'Panniyur 2', type: 'Climber', category: 'Bush Pepper', description: 'Improved vigor.', price: 145, stock: 40 },
  { name: 'Panniyur 3', type: 'Climber', category: 'Bush Pepper', description: 'Uniform spikes.', price: 150, stock: 35 },
  { name: 'Panniyur 4', type: 'Climber', category: 'Bush Pepper', description: 'Good berry size.', price: 155, stock: 30 },
  { name: 'Panniyur 5', type: 'Climber', category: 'Bush Pepper', description: 'Quality fruits.', price: 160, stock: 30 },
  { name: 'Panniyur 6', type: 'Climber', category: 'Bush Pepper', description: 'Consistent producer.', price: 165, stock: 25 },
  { name: 'Panniyur 7', type: 'Climber', category: 'Bush Pepper', description: 'Popular among growers.', price: 170, stock: 25 },
  { name: 'Panniyur 8', type: 'Climber', category: 'Bush Pepper', description: 'Strong plant health.', price: 175, stock: 20 },
  { name: 'Panniyur 9', type: 'Climber', category: 'Bush Pepper', description: 'Latest Panniyur line.', price: 180, stock: 20 },
  { name: 'Vijay', type: 'Climber', category: 'Bush Pepper', description: 'Reliable cultivar.', price: 135, stock: 40 },
  { name: 'Thekkan 1', type: 'Bush', category: 'Bush Pepper', description: 'Compact bush pepper.', price: 100, stock: 60 },
  { name: 'Thekkan 2', type: 'Bush', category: 'Bush Pepper', description: 'Bush type, easy maintenance.', price: 105, stock: 55 },
  { name: 'Neelamundi', type: 'Climber', category: 'Bush Pepper', description: 'Distinct taste.', price: 115, stock: 30 },
  { name: 'Vattamundi', type: 'Climber', category: 'Bush Pepper', description: 'Roundish spike formation.', price: 120, stock: 30 },
  { name: 'Vellamundi', type: 'Climber', category: 'Bush Pepper', description: 'Light-colored berries.', price: 120, stock: 30 },
  { name: 'Kuthiravalley', type: 'Climber', category: 'Bush Pepper', description: 'Known regional variety.', price: 125, stock: 25 },
];